version: "2"
services:
    words_service:
        build:
            context: ./WantWords
            dockerfile: Dockerfile
        image: want_words_server_image
        container_name: want_words_server_container
        restart: always
        expose:
            - 8000
        ports:
            - "8000:8000"
